class FeedbackHandler:
    """
    Manages the collection and storage of user feedback on model responses.
    """

    def __init__(self, database):
        """
        Initialize the FeedbackHandler with a database connection.
        
        Args:
            database: A database instance that provides a log_feedback method.
        """
        self.database = database
        self.current_feedback = None
        self.current_session = {}

    def store_session_data(self, usecase, user_input, model_a_name, model_b_name, 
                          model_a_response, model_b_response):
        """
        Store the current session data for later feedback submission.
        
        Args:
            usecase (str): The current use case being tested.
            user_input (str): The input provided by the user.
            model_a_name (str): The name of the first model.
            model_b_name (str): The name of the second model.
            model_a_response (str): The response generated by the first model.
            model_b_response (str): The response generated by the second model.
        """
        self.current_session.update({
            'usecase': usecase,
            'user_input': user_input,
            'model_a_name': model_a_name,
            'model_b_name': model_b_name,
            'model_a_response': model_a_response,
            'model_b_response': model_b_response
        })

    def set_feedback(self, value):
        """
        Set the user's feedback on the model responses.
        
        Args:
            value (str): The feedback value, typically indicating which model performed better.
        """
        self.current_feedback = value

    def submit_feedback(self, feedback_motivation):
        """
        Submit the collected feedback and session data to the database.
        
        Args:
            feedback_motivation (str): The user's explanation for their feedback.
            
        Returns:
            bool: True if feedback was successfully submitted, False otherwise.
        """
        if self.current_feedback and self.current_session:
            self.database.log_feedback(
                **self.current_session,
                feedback=self.current_feedback,
                feedback_motivation=feedback_motivation
            )
            return True
        return False
